# .github/workflows/cron-trigger.yml
name: Webhook Workflow

on:
  repository_dispatch:
    types: [cron_trigger]

jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: Print payload
        run: |
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
